/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sama's PC
 */
public class SignUp extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;


    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        phone = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        backH = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        email1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(617, 322));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel4.setText("Sign Up");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 90, -1));

        jPanel2.setBackground(new java.awt.Color(0,0,0,100));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 43, -1, -1));

        signN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signNActionPerformed(evt);
            }
        });
        jPanel2.add(signN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 170, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("gender");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 84, 44, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 124, 92, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SSN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 157, 29, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 185, 88, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 218, 35, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 76, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 122, 170, -1));

        SSN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 155, 170, -1));

        birthday.setForeground(new java.awt.Color(153, 153, 153));
        birthday.setText("dd/mm/yyyy");
        birthday.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayActionPerformed(evt);
            }
        });
        jPanel2.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, -1));

        city.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, -1));

        SignUp.setBackground(new java.awt.Color(204, 204, 255));
        SignUp.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.setBorder(null);
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel2.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 66, 24));

        backH.setBackground(new java.awt.Color(204, 204, 255));
        backH.setFont(new java.awt.Font("Sylfaen", 2, 11)); // NOI18N
        backH.setText("Home");
        backH.setBorder(null);
        backH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHActionPerformed(evt);
            }
        });
        jPanel2.add(backH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 47, 19));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 251, 76, -1));

        password1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, -1));

        email1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 216, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 290, 370));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\1111.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHActionPerformed
        // TODO add your handling code here:
        mainView M=new mainView();
        M.setVisible(true);
    }//GEN-LAST:event_backHActionPerformed

    private void birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void signNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signNActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
 
        try{
           
    String s="INSERT INTO PERSON (SSN_,NAME_,PHONE_,GENDER_,BIRTHDAY_,Email_,PASSWORD_,City_)values(?,?,?,?,?,?,?,?)";
   DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
     Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","c##sama","123456");
     Object varname=(String)gender.getSelectedItem();
    // gender.getSelectedItem();
     String v=gender.getSelectedItem().toString();
pst= conn.prepareStatement(s);
 pst.setString(2,signN.getText() );
 pst.setString(4,v);
 pst.setString(3,phone.getText() );
 pst.setString(1,SSN.getText() );
 pst.setString(5,birthday.getText() );
 pst.setString(6,email1.getText() );
 pst.setString(7,password1.getText() );
 pst.setString(8,city.getText() );
 pst.execute();
 JOptionPane.showMessageDialog(null, "done");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
        
    }//GEN-LAST:event_SignUpActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SSN;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton backH;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField signN;
    // End of variables declaration//GEN-END:variables
}
