/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sama's PC
 */
public class tourismTypes extends javax.swing.JFrame {

    /**
     * Creates new form tourismTypes
     */
    public tourismTypes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        foreign = new javax.swing.JButton();
        dom = new javax.swing.JButton();
        backH = new javax.swing.JButton();
        backH1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0,0,80));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Choose what are you searching for:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 20));

        foreign.setBackground(new java.awt.Color(0, 0, 0));
        foreign.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        foreign.setForeground(new java.awt.Color(255, 255, 255));
        foreign.setText("Foreign");
        foreign.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        foreign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foreignActionPerformed(evt);
            }
        });
        jPanel1.add(foreign, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        dom.setBackground(new java.awt.Color(0, 0, 0));
        dom.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        dom.setForeground(new java.awt.Color(255, 255, 255));
        dom.setText("Domestic");
        dom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domActionPerformed(evt);
            }
        });
        jPanel1.add(dom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        backH.setBackground(new java.awt.Color(0, 0, 0));
        backH.setFont(new java.awt.Font("Sylfaen", 3, 11)); // NOI18N
        backH.setForeground(new java.awt.Color(255, 255, 255));
        backH.setText("Home");
        backH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHActionPerformed(evt);
            }
        });
        jPanel1.add(backH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, -1));

        backH1.setBackground(new java.awt.Color(0, 0, 0));
        backH1.setFont(new java.awt.Font("Sylfaen", 3, 11)); // NOI18N
        backH1.setForeground(new java.awt.Color(255, 255, 255));
        backH1.setText("Back");
        backH1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backH1ActionPerformed(evt);
            }
        });
        jPanel1.add(backH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 390, 210));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\1111.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1410, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void foreignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foreignActionPerformed
        // TODO add your handling code here:
        Ftrips F =new Ftrips();
        F.setVisible(true);
    }//GEN-LAST:event_foreignActionPerformed

    private void domActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domActionPerformed
        // TODO add your handling code here:
        Domestic D=new Domestic();
        D.setVisible(true);
    }//GEN-LAST:event_domActionPerformed

    private void backHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHActionPerformed
        // TODO add your handling code here:
        mainView M=new mainView();
        M.setVisible(true);
    }//GEN-LAST:event_backHActionPerformed

    private void backH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backH1ActionPerformed
UserLogin U=new UserLogin();
U.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backH1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tourismTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tourismTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tourismTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tourismTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tourismTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backH;
    private javax.swing.JButton backH1;
    private javax.swing.JButton dom;
    private javax.swing.JButton foreign;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
