/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sama's PC
 */
public class Trips extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public Trips() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Mdet = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Mdet1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Edetailes2 = new javax.swing.JButton();
        Idetails = new javax.swing.JButton();
        Tdetails = new javax.swing.JButton();
        Sdetails = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Bdet = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ThDet = new javax.swing.JButton();
        SAdet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        backH = new javax.swing.JButton();
        backH1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel6.setText("Cairo-Egypt");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        Mdet.setBackground(new java.awt.Color(0, 0, 0));
        Mdet.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Mdet.setForeground(new java.awt.Color(255, 255, 255));
        Mdet.setText("Details");
        Mdet.setBorder(null);
        Mdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdetActionPerformed(evt);
            }
        });
        jPanel1.add(Mdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 50, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\Cairo-egypt-camels-and-pyramids.jpg")); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 210, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\Downloads\\spain.jpeg")); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 220, 140));

        Mdet1.setBackground(new java.awt.Color(0, 0, 0));
        Mdet1.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Mdet1.setForeground(new java.awt.Color(255, 255, 255));
        Mdet1.setText("Details");
        Mdet1.setBorder(null);
        Mdet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mdet1ActionPerformed(evt);
            }
        });
        jPanel1.add(Mdet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 50, 20));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel16.setText("Dubai-UAE");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 220, 80, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\dubai-is-a-beautiful.jpg")); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 210, 140));

        Edetailes2.setBackground(new java.awt.Color(0, 0, 0));
        Edetailes2.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Edetailes2.setForeground(new java.awt.Color(255, 255, 255));
        Edetailes2.setText("Details");
        Edetailes2.setBorder(null);
        Edetailes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edetailes2ActionPerformed(evt);
            }
        });
        jPanel1.add(Edetailes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 50, 20));

        Idetails.setBackground(new java.awt.Color(0, 0, 0));
        Idetails.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Idetails.setForeground(new java.awt.Color(255, 255, 255));
        Idetails.setText("Deails");
        Idetails.setBorder(null);
        Idetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Idetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 50, 20));

        Tdetails.setBackground(new java.awt.Color(0, 0, 0));
        Tdetails.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Tdetails.setForeground(new java.awt.Color(255, 255, 255));
        Tdetails.setText("Details");
        Tdetails.setBorder(null);
        Tdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Tdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 50, -1));

        Sdetails.setBackground(new java.awt.Color(0, 0, 0));
        Sdetails.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Sdetails.setForeground(new java.awt.Color(255, 255, 255));
        Sdetails.setText("Details");
        Sdetails.setBorder(null);
        Sdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Sdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 50, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\double-decker-london (1).jpg")); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 210, 140));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("London-England");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 120, -1));

        jLabel15.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel15.setText("Beriut-Lebanon");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\Beirut.jpg")); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 480, 210, 130));

        Bdet.setBackground(new java.awt.Color(0, 0, 0));
        Bdet.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        Bdet.setForeground(new java.awt.Color(255, 255, 255));
        Bdet.setText("Details");
        Bdet.setBorder(null);
        Bdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetActionPerformed(evt);
            }
        });
        jPanel1.add(Bdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 50, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\thailand-6 (1).jpg")); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 210, 130));

        ThDet.setBackground(new java.awt.Color(0, 0, 0));
        ThDet.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        ThDet.setForeground(new java.awt.Color(255, 255, 255));
        ThDet.setText("Details");
        ThDet.setBorder(null);
        ThDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThDetActionPerformed(evt);
            }
        });
        jPanel1.add(ThDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 50, -1));

        SAdet.setBackground(new java.awt.Color(0, 0, 0));
        SAdet.setFont(new java.awt.Font("Sylfaen", 3, 12)); // NOI18N
        SAdet.setForeground(new java.awt.Color(255, 255, 255));
        SAdet.setText("Deails");
        SAdet.setBorder(null);
        SAdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAdetActionPerformed(evt);
            }
        });
        jPanel1.add(SAdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel2.setText("Barcelona-Spain");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("Istanbul-Turkey");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\Turkey.jpg")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\italy_rome_flag.jpg")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, 150));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel8.setText("Rome-Italy");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel12.setText("Bangkok-Thailand");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 120, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sama's PC\\OneDrive\\Desktop\\New folder (2)\\southafrica .jpg")); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 210, 130));

        jLabel19.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel19.setText("Cape Town-South Africa");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        Next.setBackground(new java.awt.Color(0, 0, 0));
        Next.setFont(new java.awt.Font("Sylfaen", 3, 13)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setText("Back");
        Next.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 140, -1));

        backH.setBackground(new java.awt.Color(0, 0, 0));
        backH.setFont(new java.awt.Font("Sylfaen", 3, 13)); // NOI18N
        backH.setForeground(new java.awt.Color(255, 255, 255));
        backH.setText("Home");
        backH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHActionPerformed(evt);
            }
        });
        jPanel1.add(backH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 130, -1));

        backH1.setBackground(new java.awt.Color(0, 0, 0));
        backH1.setFont(new java.awt.Font("Sylfaen", 3, 11)); // NOI18N
        backH1.setForeground(new java.awt.Color(255, 255, 255));
        backH1.setText("next");
        backH1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backH1ActionPerformed(evt);
            }
        });
        jPanel1.add(backH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(jLabel1)
                .addContainerGap(800, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(660, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdetActionPerformed
        Cairo C=new Cairo();
        C.setVisible(true);
    }//GEN-LAST:event_MdetActionPerformed

    private void Mdet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mdet1ActionPerformed
        // TODO add your handling code here:
        Dubai D=new Dubai();
        D.setVisible(true);
    }//GEN-LAST:event_Mdet1ActionPerformed

    private void Edetailes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edetailes2ActionPerformed
        // TODO add your handling code here:
        London L=new London();
        L.setVisible(true);
    }//GEN-LAST:event_Edetailes2ActionPerformed

    private void IdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdetailsActionPerformed
        // TODO add your handling code here:
        Rome R=new Rome();
        R.setVisible(true);
    }//GEN-LAST:event_IdetailsActionPerformed

    private void TdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdetailsActionPerformed
        // TODO add your handling code here:
        istanbulA I=new istanbulA();
        I.setVisible(true);

    }//GEN-LAST:event_TdetailsActionPerformed

    private void SdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdetailsActionPerformed
        // TODO add your handling code here:

        Barcelona B=new Barcelona();
        B.setVisible(true);
    }//GEN-LAST:event_SdetailsActionPerformed

    private void BdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetActionPerformed
        Beirut B = new Beirut();
        B.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BdetActionPerformed

    private void ThDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThDetActionPerformed
        Thailand t=new Thailand ();
        t.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ThDetActionPerformed

    private void SAdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAdetActionPerformed
        Africa a=new Africa();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SAdetActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        Admin F=new Admin();
        F.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    private void backHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHActionPerformed
        // TODO add your handling code here:
        mainView M=new mainView();
        M.setVisible(true);
    }//GEN-LAST:event_backHActionPerformed

    private void backH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backH1ActionPerformed
next N=new next();
N.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backH1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdet;
    private javax.swing.JButton Edetailes2;
    private javax.swing.JButton Idetails;
    private javax.swing.JButton Mdet;
    private javax.swing.JButton Mdet1;
    private javax.swing.JButton Next;
    private javax.swing.JButton SAdet;
    private javax.swing.JButton Sdetails;
    private javax.swing.JButton Tdetails;
    private javax.swing.JButton ThDet;
    private javax.swing.JButton backH;
    private javax.swing.JButton backH1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
